# Generated by Django 3.2.8 on 2021-12-09 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route_shedule',
            name='arrival_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route_shedule',
            name='departure_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route_shedule',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='route_shedule',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
