# Generated by Django 3.2.8 on 2021-12-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20211209_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route_shedule',
            name='delay_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='route_shedule',
            name='flight_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
