# Generated by Django 3.2.8 on 2021-12-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20211210_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='route_shedule',
            name='flight_delay',
            field=models.TimeField(null=True),
        ),
    ]
