# Generated by Django 3.2.14 on 2023-04-18 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_auto_20230418_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='filght',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.route_shedule'),
        ),
    ]
