# Generated by Django 3.2.8 on 2021-12-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquery',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('enquery_airport', models.CharField(max_length=100)),
                ('enquery_subject', models.CharField(max_length=200)),
                ('enquery_enquery', models.CharField(max_length=1000)),
                ('enquery_date', models.DateTimeField(auto_now_add=True)),
                ('enquery_answer', models.CharField(max_length=1000, null=True)),
                ('answer_date', models.DateTimeField(null=True)),
                ('referrences', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
